
spring:
  rocketmq:
    topic: T_yangkaihu_test
    nameserver: 192.168.100.110:9776;192.168.100.110:9778
    sendMessageTimeout: 3000
    retryTimesWhenSendAsyncFailed: 3
    maxMessageSize: 4194304
    compressMsgBodyOverHowmuch: 4096
    retryAnotherBrokerWhenNotStoreOk: true


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha          # ???????
    operations-sorter: alpha    # ???????
    display-request-duration: true
  default-produces-media-type: application/json
server:
  port: 4567


management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: duudle
